# @format

# .github/workflows/tests.yml
services:
  postgres:
    image: postgres:15-alpine
    env:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5432:5432
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

steps:
  - run: DATABASE_URL=postgres://test:test@localhost/test sqlx migrate run
  - run: DATABASE_URL=postgres://test:test@localhost/test cargo test
